language: android

jdk:
 - oraclejdk7
 - oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository

script:
  - ./gradlew clean check -Dpre-dex=false

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
